// Generated by `scripts/generate-emoji-data.js`. DO NOT EDIT.

/**
 * Emoji list from `emoji-data` v16.0.0, in the Unicode order the dataset publishes.
 *
 * One line per emoji, made up of tab-separated fields: the emoji character, its shortcodes, and any
 * further searchable words taken from its Unicode name. Multiple shortcodes or keywords within a
 * field are separated by a space, and the last field is left out when there are no extra keywords.
 * The first shortcode is the canonical one, the one shown alongside the emoji in the suggestions.
 *
 * It’s a single string rather than an object so that it costs one line per emoji in the bundle
 * instead of a few hundred bytes of punctuation, and so that nothing is parsed until the first
 * shortcode is actually typed.
 * @see https://github.com/iamcal/emoji-data
 */
export const EMOJI_DATA = `😀	grinning	face
😃	smiley	smiling face open mouth
😄	smile	smiling face open mouth eyes
😁	grin	grinning face smiling eyes
😆	laughing satisfied	smiling face open mouth tightly-closed eyes
😅	sweat_smile	smiling face open mouth cold
🤣	rolling_on_the_floor_laughing
😂	joy	face tears
🙂	slightly_smiling_face
🙃	upside_down_face	upside-down
🫠	melting_face
😉	wink	winking face
😊	blush	smiling face eyes
😇	innocent	smiling face halo
🥰	smiling_face_with_3_hearts	eyes three
😍	heart_eyes	smiling face heart-shaped
🤩	star-struck grinning_face_with_star_eyes
😘	kissing_heart	face throwing kiss
😗	kissing	face
☺️	relaxed	white smiling face
😚	kissing_closed_eyes	face
😙	kissing_smiling_eyes	face
🥲	smiling_face_with_tear
😋	yum	face savouring delicious food
😛	stuck_out_tongue	face stuck-out
😜	stuck_out_tongue_winking_eye	face stuck-out
🤪	zany_face grinning_face_with_one_large_and_one_small_eye
😝	stuck_out_tongue_closed_eyes	face stuck-out tightly-closed
🤑	money_mouth_face	money-mouth
🤗	hugging_face
🤭	face_with_hand_over_mouth smiling_face_with_smiling_eyes_and_hand_covering_mouth
🫢	face_with_open_eyes_and_hand_over_mouth
🫣	face_with_peeking_eye
🤫	shushing_face face_with_finger_covering_closed_lips
🤔	thinking_face
🫡	saluting_face
🤐	zipper_mouth_face	zipper-mouth
🤨	face_with_raised_eyebrow face_with_one_eyebrow_raised
😐	neutral_face
😑	expressionless	face
😶	no_mouth	face without
🫥	dotted_line_face
😶‍🌫️	face_in_clouds
😏	smirk	smirking face
😒	unamused	face
🙄	face_with_rolling_eyes
😬	grimacing	face
😮‍💨	face_exhaling
🤥	lying_face
🫨	shaking_face
🙂‍↔️	head_shaking_horizontally
🙂‍↕️	head_shaking_vertically
😌	relieved	face
😔	pensive	face
😪	sleepy	face
🤤	drooling_face
😴	sleeping	face
🫩	face_with_bags_under_eyes
😷	mask	face medical
🤒	face_with_thermometer
🤕	face_with_head_bandage	head-bandage
🤢	nauseated_face
🤮	face_vomiting face_with_open_mouth_vomiting
🤧	sneezing_face
🥵	hot_face	overheated
🥶	cold_face	freezing
🥴	woozy_face	uneven eyes wavy mouth
😵	dizzy_face
😵‍💫	face_with_spiral_eyes
🤯	exploding_head shocked_face_with_exploding_head
🤠	face_with_cowboy_hat
🥳	partying_face	party horn hat
🥸	disguised_face
😎	sunglasses	smiling face
🤓	nerd_face
🧐	face_with_monocle
😕	confused	face
🫤	face_with_diagonal_mouth
😟	worried	face
🙁	slightly_frowning_face
☹️	white_frowning_face
😮	open_mouth	face
😯	hushed	face
😲	astonished	face
😳	flushed	face
🥺	pleading_face	eyes
🥹	face_holding_back_tears
😦	frowning	face open mouth
😧	anguished	face
😨	fearful	face
😰	cold_sweat	face open mouth
😥	disappointed_relieved	but face
😢	cry	crying face
😭	sob	loudly crying face
😱	scream	face screaming fear
😖	confounded	face
😣	persevere	persevering face
😞	disappointed	face
😓	sweat	face cold
😩	weary	face
😫	tired_face
🥱	yawning_face
😤	triumph	face look
😡	rage	pouting face
😠	angry	face
🤬	face_with_symbols_on_mouth serious_face_with_symbols_covering_mouth
😈	smiling_imp	face horns
👿	imp
💀	skull
☠️	skull_and_crossbones
💩	hankey poop shit	pile poo
🤡	clown_face
👹	japanese_ogre
👺	japanese_goblin
👻	ghost
👽	alien	extraterrestrial
👾	space_invader	alien monster
🤖	robot_face
😺	smiley_cat	smiling face open mouth
😸	smile_cat	grinning face smiling eyes
😹	joy_cat	face tears
😻	heart_eyes_cat	smiling face heart-shaped
😼	smirk_cat	face wry smile
😽	kissing_cat	face closed eyes
🙀	scream_cat	weary face
😿	crying_cat_face
😾	pouting_cat	face
🙈	see_no_evil	see-no-evil monkey
🙉	hear_no_evil	hear-no-evil monkey
🙊	speak_no_evil	speak-no-evil monkey
💌	love_letter
💘	cupid	heart arrow
💝	gift_heart	ribbon
💖	sparkling_heart
💗	heartpulse	growing heart
💓	heartbeat	beating heart
💞	revolving_hearts
💕	two_hearts
💟	heart_decoration
❣️	heavy_heart_exclamation_mark_ornament
💔	broken_heart
❤️‍🔥	heart_on_fire
❤️‍🩹	mending_heart
❤️	heart	heavy black
🩷	pink_heart
🧡	orange_heart
💛	yellow_heart
💚	green_heart
💙	blue_heart
🩵	light_blue_heart
💜	purple_heart
🤎	brown_heart
🖤	black_heart
🩶	grey_heart
🤍	white_heart
💋	kiss	mark
💯	100	hundred points symbol
💢	anger	symbol
💥	boom collision	symbol
💫	dizzy	symbol
💦	sweat_drops	splashing symbol
💨	dash	symbol
🕳️	hole
💬	speech_balloon
👁️‍🗨️	eye-in-speech-bubble
🗨️	left_speech_bubble
🗯️	right_anger_bubble
💭	thought_balloon
💤	zzz	sleeping symbol
👋	wave	waving hand sign
🤚	raised_back_of_hand
🖐️	raised_hand_with_fingers_splayed
✋	hand raised_hand
🖖	spock-hand	raised part between middle ring fingers
🫱	rightwards_hand
🫲	leftwards_hand
🫳	palm_down_hand
🫴	palm_up_hand
🫷	leftwards_pushing_hand
🫸	rightwards_pushing_hand
👌	ok_hand	sign
🤌	pinched_fingers
🤏	pinching_hand
✌️	v	victory hand
🤞	crossed_fingers hand_with_index_and_middle_fingers_crossed
🫰	hand_with_index_finger_and_thumb_crossed
🤟	i_love_you_hand_sign
🤘	the_horns sign_of_the_horns
🤙	call_me_hand
👈	point_left	white pointing backhand index
👉	point_right	white pointing backhand index
👆	point_up_2	white pointing backhand index
🖕	middle_finger reversed_hand_with_middle_finger_extended
👇	point_down	white pointing backhand index
☝️	point_up	white pointing index
🫵	index_pointing_at_the_viewer
👍	+1 thumbsup	thumbs up sign
👎	-1 thumbsdown	thumbs down sign
✊	fist	raised
👊	facepunch punch	fisted hand sign
🤛	left-facing_fist	left-facing
🤜	right-facing_fist	right-facing
👏	clap	clapping hands sign
🙌	raised_hands	person raising both celebration
🫶	heart_hands
👐	open_hands	sign
🤲	palms_up_together
🤝	handshake
🙏	pray	person folded hands
✍️	writing_hand
💅	nail_care	polish
🤳	selfie
💪	muscle	flexed biceps
🦾	mechanical_arm
🦿	mechanical_leg
🦵	leg
🦶	foot
👂	ear
🦻	ear_with_hearing_aid
👃	nose
🧠	brain
🫀	anatomical_heart
🫁	lungs
🦷	tooth
🦴	bone
👀	eyes
👁️	eye
👅	tongue
👄	lips	mouth
🫦	biting_lip
👶	baby
🧒	child
👦	boy
👧	girl
🧑	adult
👱	person_with_blond_hair
👨	man
🧔	bearded_person
🧔‍♂️	man_with_beard
🧔‍♀️	woman_with_beard
👨‍🦰	red_haired_man	hair
👨‍🦱	curly_haired_man	hair
👨‍🦳	white_haired_man	hair
👨‍🦲	bald_man
👩	woman
👩‍🦰	red_haired_woman	hair
🧑‍🦰	red_haired_person	hair
👩‍🦱	curly_haired_woman	hair
🧑‍🦱	curly_haired_person	hair
👩‍🦳	white_haired_woman	hair
🧑‍🦳	white_haired_person	hair
👩‍🦲	bald_woman
🧑‍🦲	bald_person
👱‍♀️	blond-haired-woman	hair
👱‍♂️	blond-haired-man	hair
🧓	older_adult
👴	older_man
👵	older_woman
🙍	person_frowning
🙍‍♂️	man-frowning
🙍‍♀️	woman-frowning
🙎	person_with_pouting_face
🙎‍♂️	man-pouting
🙎‍♀️	woman-pouting
🙅	no_good	face gesture
🙅‍♂️	man-gesturing-no
🙅‍♀️	woman-gesturing-no
🙆	ok_woman	face gesture
🙆‍♂️	man-gesturing-ok
🙆‍♀️	woman-gesturing-ok
💁	information_desk_person
💁‍♂️	man-tipping-hand
💁‍♀️	woman-tipping-hand
🙋	raising_hand	happy person one
🙋‍♂️	man-raising-hand
🙋‍♀️	woman-raising-hand
🧏	deaf_person
🧏‍♂️	deaf_man
🧏‍♀️	deaf_woman
🙇	bow	person bowing deeply
🙇‍♂️	man-bowing
🙇‍♀️	woman-bowing
🤦	face_palm
🤦‍♂️	man-facepalming
🤦‍♀️	woman-facepalming
🤷	shrug
🤷‍♂️	man-shrugging
🤷‍♀️	woman-shrugging
🧑‍⚕️	health_worker
👨‍⚕️	male-doctor	man health worker
👩‍⚕️	female-doctor	woman health worker
🧑‍🎓	student
👨‍🎓	male-student	man
👩‍🎓	female-student	woman
🧑‍🏫	teacher
👨‍🏫	male-teacher	man
👩‍🏫	female-teacher	woman
🧑‍⚖️	judge
👨‍⚖️	male-judge	man
👩‍⚖️	female-judge	woman
🧑‍🌾	farmer
👨‍🌾	male-farmer	man
👩‍🌾	female-farmer	woman
🧑‍🍳	cook
👨‍🍳	male-cook	man
👩‍🍳	female-cook	woman
🧑‍🔧	mechanic
👨‍🔧	male-mechanic	man
👩‍🔧	female-mechanic	woman
🧑‍🏭	factory_worker
👨‍🏭	male-factory-worker	man
👩‍🏭	female-factory-worker	woman
🧑‍💼	office_worker
👨‍💼	male-office-worker	man
👩‍💼	female-office-worker	woman
🧑‍🔬	scientist
👨‍🔬	male-scientist	man
👩‍🔬	female-scientist	woman
🧑‍💻	technologist
👨‍💻	male-technologist	man
👩‍💻	female-technologist	woman
🧑‍🎤	singer
👨‍🎤	male-singer	man
👩‍🎤	female-singer	woman
🧑‍🎨	artist
👨‍🎨	male-artist	man
👩‍🎨	female-artist	woman
🧑‍✈️	pilot
👨‍✈️	male-pilot	man
👩‍✈️	female-pilot	woman
🧑‍🚀	astronaut
👨‍🚀	male-astronaut	man
👩‍🚀	female-astronaut	woman
🧑‍🚒	firefighter
👨‍🚒	male-firefighter	man
👩‍🚒	female-firefighter	woman
👮	cop	police officer
👮‍♂️	male-police-officer	man
👮‍♀️	female-police-officer	woman
🕵️	sleuth_or_spy	detective
🕵️‍♂️	male-detective	man
🕵️‍♀️	female-detective	woman
💂	guardsman
💂‍♂️	male-guard	man
💂‍♀️	female-guard	woman
🥷	ninja
👷	construction_worker
👷‍♂️	male-construction-worker	man
👷‍♀️	female-construction-worker	woman
🫅	person_with_crown
🤴	prince
👸	princess
👳	man_with_turban
👳‍♂️	man-wearing-turban
👳‍♀️	woman-wearing-turban
👲	man_with_gua_pi_mao
🧕	person_with_headscarf
🤵	person_in_tuxedo	man
🤵‍♂️	man_in_tuxedo
🤵‍♀️	woman_in_tuxedo
👰	bride_with_veil
👰‍♂️	man_with_veil
👰‍♀️	woman_with_veil
🤰	pregnant_woman
🫃	pregnant_man
🫄	pregnant_person
🤱	breast-feeding
👩‍🍼	woman_feeding_baby
👨‍🍼	man_feeding_baby
🧑‍🍼	person_feeding_baby
👼	angel	baby
🎅	santa	father christmas
🤶	mrs_claus mother_christmas
🧑‍🎄	mx_claus
🦸	superhero
🦸‍♂️	male_superhero	man
🦸‍♀️	female_superhero	woman
🦹	supervillain
🦹‍♂️	male_supervillain	man
🦹‍♀️	female_supervillain	woman
🧙	mage
🧙‍♂️	male_mage	man
🧙‍♀️	female_mage	woman
🧚	fairy
🧚‍♂️	male_fairy	man
🧚‍♀️	female_fairy	woman
🧛	vampire
🧛‍♂️	male_vampire	man
🧛‍♀️	female_vampire	woman
🧜	merperson
🧜‍♂️	merman
🧜‍♀️	mermaid
🧝	elf
🧝‍♂️	male_elf	man
🧝‍♀️	female_elf	woman
🧞	genie
🧞‍♂️	male_genie	man
🧞‍♀️	female_genie	woman
🧟	zombie
🧟‍♂️	male_zombie	man
🧟‍♀️	female_zombie	woman
🧌	troll
💆	massage	face
💆‍♂️	man-getting-massage
💆‍♀️	woman-getting-massage
💇	haircut
💇‍♂️	man-getting-haircut
💇‍♀️	woman-getting-haircut
🚶	walking	pedestrian
🚶‍♂️	man-walking
🚶‍♀️	woman-walking
🚶‍➡️	person_walking_facing_right
🚶‍♀️‍➡️	woman_walking_facing_right
🚶‍♂️‍➡️	man_walking_facing_right
🧍	standing_person
🧍‍♂️	man_standing
🧍‍♀️	woman_standing
🧎	kneeling_person
🧎‍♂️	man_kneeling
🧎‍♀️	woman_kneeling
🧎‍➡️	person_kneeling_facing_right
🧎‍♀️‍➡️	woman_kneeling_facing_right
🧎‍♂️‍➡️	man_kneeling_facing_right
🧑‍🦯	person_with_probing_cane	white
🧑‍🦯‍➡️	person_with_white_cane_facing_right
👨‍🦯	man_with_probing_cane	white
👨‍🦯‍➡️	man_with_white_cane_facing_right
👩‍🦯	woman_with_probing_cane	white
👩‍🦯‍➡️	woman_with_white_cane_facing_right
🧑‍🦼	person_in_motorized_wheelchair
🧑‍🦼‍➡️	person_in_motorized_wheelchair_facing_right
👨‍🦼	man_in_motorized_wheelchair
👨‍🦼‍➡️	man_in_motorized_wheelchair_facing_right
👩‍🦼	woman_in_motorized_wheelchair
👩‍🦼‍➡️	woman_in_motorized_wheelchair_facing_right
🧑‍🦽	person_in_manual_wheelchair
🧑‍🦽‍➡️	person_in_manual_wheelchair_facing_right
👨‍🦽	man_in_manual_wheelchair
👨‍🦽‍➡️	man_in_manual_wheelchair_facing_right
👩‍🦽	woman_in_manual_wheelchair
👩‍🦽‍➡️	woman_in_manual_wheelchair_facing_right
🏃	runner running
🏃‍♂️	man-running
🏃‍♀️	woman-running
🏃‍➡️	person_running_facing_right
🏃‍♀️‍➡️	woman_running_facing_right
🏃‍♂️‍➡️	man_running_facing_right
💃	dancer
🕺	man_dancing
🕴️	man_in_business_suit_levitating	person
👯	dancers	woman bunny ears
👯‍♂️	men-with-bunny-ears-partying man-with-bunny-ears-partying
👯‍♀️	women-with-bunny-ears-partying woman-with-bunny-ears-partying
🧖	person_in_steamy_room
🧖‍♂️	man_in_steamy_room
🧖‍♀️	woman_in_steamy_room
🧗	person_climbing
🧗‍♂️	man_climbing
🧗‍♀️	woman_climbing
🤺	fencer
🏇	horse_racing
⛷️	skier
🏂	snowboarder
🏌️	golfer	person golfing
🏌️‍♂️	man-golfing
🏌️‍♀️	woman-golfing
🏄	surfer
🏄‍♂️	man-surfing
🏄‍♀️	woman-surfing
🚣	rowboat
🚣‍♂️	man-rowing-boat
🚣‍♀️	woman-rowing-boat
🏊	swimmer
🏊‍♂️	man-swimming
🏊‍♀️	woman-swimming
⛹️	person_with_ball	bouncing
⛹️‍♂️	man-bouncing-ball
⛹️‍♀️	woman-bouncing-ball
🏋️	weight_lifter	person lifting weights
🏋️‍♂️	man-lifting-weights
🏋️‍♀️	woman-lifting-weights
🚴	bicyclist
🚴‍♂️	man-biking
🚴‍♀️	woman-biking
🚵	mountain_bicyclist
🚵‍♂️	man-mountain-biking
🚵‍♀️	woman-mountain-biking
🤸	person_doing_cartwheel
🤸‍♂️	man-cartwheeling
🤸‍♀️	woman-cartwheeling
🤼	wrestlers
🤼‍♂️	man-wrestling	men
🤼‍♀️	woman-wrestling	women
🤽	water_polo
🤽‍♂️	man-playing-water-polo
🤽‍♀️	woman-playing-water-polo
🤾	handball
🤾‍♂️	man-playing-handball
🤾‍♀️	woman-playing-handball
🤹	juggling
🤹‍♂️	man-juggling
🤹‍♀️	woman-juggling
🧘	person_in_lotus_position
🧘‍♂️	man_in_lotus_position
🧘‍♀️	woman_in_lotus_position
🛀	bath
🛌	sleeping_accommodation
🧑‍🤝‍🧑	people_holding_hands
👭	two_women_holding_hands women_holding_hands
👫	man_and_woman_holding_hands woman_and_man_holding_hands couple
👬	two_men_holding_hands men_holding_hands
💏	couplekiss	kiss
👩‍❤️‍💋‍👨	woman-kiss-man
👨‍❤️‍💋‍👨	man-kiss-man
👩‍❤️‍💋‍👩	woman-kiss-woman
💑	couple_with_heart
👩‍❤️‍👨	woman-heart-man	couple
👨‍❤️‍👨	man-heart-man	couple
👩‍❤️‍👩	woman-heart-woman	couple
👨‍👩‍👦	man-woman-boy	family
👨‍👩‍👧	man-woman-girl	family
👨‍👩‍👧‍👦	man-woman-girl-boy	family
👨‍👩‍👦‍👦	man-woman-boy-boy	family
👨‍👩‍👧‍👧	man-woman-girl-girl	family
👨‍👨‍👦	man-man-boy	family
👨‍👨‍👧	man-man-girl	family
👨‍👨‍👧‍👦	man-man-girl-boy	family
👨‍👨‍👦‍👦	man-man-boy-boy	family
👨‍👨‍👧‍👧	man-man-girl-girl	family
👩‍👩‍👦	woman-woman-boy	family
👩‍👩‍👧	woman-woman-girl	family
👩‍👩‍👧‍👦	woman-woman-girl-boy	family
👩‍👩‍👦‍👦	woman-woman-boy-boy	family
👩‍👩‍👧‍👧	woman-woman-girl-girl	family
👨‍👦	man-boy	family
👨‍👦‍👦	man-boy-boy	family
👨‍👧	man-girl	family
👨‍👧‍👦	man-girl-boy	family
👨‍👧‍👧	man-girl-girl	family
👩‍👦	woman-boy	family
👩‍👦‍👦	woman-boy-boy	family
👩‍👧	woman-girl	family
👩‍👧‍👦	woman-girl-boy	family
👩‍👧‍👧	woman-girl-girl	family
🗣️	speaking_head_in_silhouette
👤	bust_in_silhouette
👥	busts_in_silhouette
🫂	people_hugging
👪	family
🧑‍🧑‍🧒	family_adult_adult_child
🧑‍🧑‍🧒‍🧒	family_adult_adult_child_child
🧑‍🧒	family_adult_child
🧑‍🧒‍🧒	family_adult_child_child
👣	footprints
🫆	fingerprint
🐵	monkey_face
🐒	monkey
🦍	gorilla
🦧	orangutan
🐶	dog	face
🐕	dog2	dog
🦮	guide_dog
🐕‍🦺	service_dog
🐩	poodle
🐺	wolf	face
🦊	fox_face
🦝	raccoon
🐱	cat	face
🐈	cat2	cat
🐈‍⬛	black_cat
🦁	lion_face
🐯	tiger	face
🐅	tiger2	tiger
🐆	leopard
🐴	horse	face
🫎	moose
🫏	donkey
🐎	racehorse	horse
🦄	unicorn_face
🦓	zebra_face
🦌	deer
🦬	bison
🐮	cow	face
🐂	ox
🐃	water_buffalo
🐄	cow2	cow
🐷	pig	face
🐖	pig2	pig
🐗	boar
🐽	pig_nose
🐏	ram
🐑	sheep
🐐	goat
🐪	dromedary_camel
🐫	camel	bactrian
🦙	llama
🦒	giraffe_face
🐘	elephant
🦣	mammoth
🦏	rhinoceros
🦛	hippopotamus
🐭	mouse	face
🐁	mouse2	mouse
🐀	rat
🐹	hamster	face
🐰	rabbit	face
🐇	rabbit2	rabbit
🐿️	chipmunk
🦫	beaver
🦔	hedgehog
🦇	bat
🐻	bear	face
🐻‍❄️	polar_bear
🐨	koala
🐼	panda_face
🦥	sloth
🦦	otter
🦨	skunk
🦘	kangaroo
🦡	badger
🐾	feet paw_prints
🦃	turkey
🐔	chicken
🐓	rooster
🐣	hatching_chick
🐤	baby_chick
🐥	hatched_chick	front-facing baby
🐦	bird
🐧	penguin
🕊️	dove_of_peace
🦅	eagle
🦆	duck
🦢	swan
🦉	owl
🦤	dodo
🪶	feather
🦩	flamingo
🦚	peacock
🦜	parrot
🪽	wing
🐦‍⬛	black_bird
🪿	goose
🐦‍🔥	phoenix
🐸	frog	face
🐊	crocodile
🐢	turtle
🦎	lizard
🐍	snake
🐲	dragon_face
🐉	dragon
🦕	sauropod
🦖	t-rex
🐳	whale	spouting
🐋	whale2	whale
🐬	dolphin flipper
🦭	seal
🐟	fish
🐠	tropical_fish
🐡	blowfish
🦈	shark
🐙	octopus
🐚	shell	spiral
🪸	coral
🪼	jellyfish
🦀	crab
🦞	lobster
🦐	shrimp
🦑	squid
🦪	oyster
🐌	snail
🦋	butterfly
🐛	bug
🐜	ant
🐝	bee honeybee
🪲	beetle
🐞	ladybug lady_beetle
🦗	cricket
🪳	cockroach
🕷️	spider
🕸️	spider_web
🦂	scorpion
🦟	mosquito
🪰	fly
🪱	worm
🦠	microbe
💐	bouquet
🌸	cherry_blossom
💮	white_flower
🪷	lotus
🏵️	rosette
🌹	rose
🥀	wilted_flower
🌺	hibiscus
🌻	sunflower
🌼	blossom
🌷	tulip
🪻	hyacinth
🌱	seedling
🪴	potted_plant
🌲	evergreen_tree
🌳	deciduous_tree
🌴	palm_tree
🌵	cactus
🌾	ear_of_rice
🌿	herb
☘️	shamrock
🍀	four_leaf_clover
🍁	maple_leaf
🍂	fallen_leaf
🍃	leaves	leaf fluttering wind
🪹	empty_nest
🪺	nest_with_eggs
🍄	mushroom
🪾	leafless_tree
🍇	grapes
🍈	melon
🍉	watermelon
🍊	tangerine
🍋	lemon
🍋‍🟩	lime
🍌	banana
🍍	pineapple
🥭	mango
🍎	apple	red
🍏	green_apple
🍐	pear
🍑	peach
🍒	cherries
🍓	strawberry
🫐	blueberries
🥝	kiwifruit
🍅	tomato
🫒	olive
🥥	coconut
🥑	avocado
🍆	eggplant	aubergine
🥔	potato
🥕	carrot
🌽	corn	ear maize
🌶️	hot_pepper
🫑	bell_pepper
🥒	cucumber
🥬	leafy_green
🥦	broccoli
🧄	garlic
🧅	onion
🥜	peanuts
🫘	beans
🌰	chestnut
🫚	ginger_root
🫛	pea_pod
🍄‍🟫	brown_mushroom
🫜	root_vegetable
🍞	bread
🥐	croissant
🥖	baguette_bread
🫓	flatbread
🥨	pretzel
🥯	bagel
🥞	pancakes
🧇	waffle
🧀	cheese_wedge
🍖	meat_on_bone
🍗	poultry_leg
🥩	cut_of_meat
🥓	bacon
🍔	hamburger
🍟	fries	french
🍕	pizza	slice
🌭	hotdog	hot dog
🥪	sandwich
🌮	taco
🌯	burrito
🫔	tamale
🥙	stuffed_flatbread
🧆	falafel
🥚	egg
🍳	fried_egg cooking
🥘	shallow_pan_of_food
🍲	stew	pot food
🫕	fondue
🥣	bowl_with_spoon
🥗	green_salad
🍿	popcorn
🧈	butter
🧂	salt	shaker
🥫	canned_food
🍱	bento	box
🍘	rice_cracker
🍙	rice_ball
🍚	rice	cooked
🍛	curry	rice
🍜	ramen	steaming bowl
🍝	spaghetti
🍠	sweet_potato	roasted
🍢	oden
🍣	sushi
🍤	fried_shrimp
🍥	fish_cake	swirl design
🥮	moon_cake
🍡	dango
🥟	dumpling
🥠	fortune_cookie
🥡	takeout_box
🍦	icecream	soft ice cream
🍧	shaved_ice
🍨	ice_cream
🍩	doughnut
🍪	cookie
🎂	birthday	cake
🍰	cake	shortcake
🧁	cupcake
🥧	pie
🍫	chocolate_bar
🍬	candy
🍭	lollipop
🍮	custard
🍯	honey_pot
🍼	baby_bottle
🥛	glass_of_milk
☕	coffee	hot beverage
🫖	teapot
🍵	tea	teacup without handle
🍶	sake	bottle cup
🍾	champagne	bottle popping cork
🍷	wine_glass
🍸	cocktail	glass
🍹	tropical_drink
🍺	beer	mug
🍻	beers	clinking beer mugs
🥂	clinking_glasses
🥃	tumbler_glass
🫗	pouring_liquid
🥤	cup_with_straw
🧋	bubble_tea
🧃	beverage_box
🧉	mate_drink
🧊	ice_cube
🥢	chopsticks
🍽️	knife_fork_plate
🍴	fork_and_knife
🥄	spoon
🔪	hocho knife
🫙	jar
🏺	amphora
🌍	earth_africa	globe europe-africa
🌎	earth_americas	globe
🌏	earth_asia	globe asia-australia
🌐	globe_with_meridians
🗺️	world_map
🗾	japan	silhouette
🧭	compass
🏔️	snow_capped_mountain	snow-capped
⛰️	mountain
🌋	volcano
🗻	mount_fuji
🏕️	camping
🏖️	beach_with_umbrella
🏜️	desert
🏝️	desert_island
🏞️	national_park
🏟️	stadium
🏛️	classical_building
🏗️	building_construction
🧱	bricks	brick
🪨	rock
🪵	wood
🛖	hut
🏘️	house_buildings	houses
🏚️	derelict_house_building
🏠	house	building
🏡	house_with_garden
🏢	office	building
🏣	post_office	japanese
🏤	european_post_office
🏥	hospital
🏦	bank
🏨	hotel
🏩	love_hotel
🏪	convenience_store
🏫	school
🏬	department_store
🏭	factory
🏯	japanese_castle
🏰	european_castle
💒	wedding
🗼	tokyo_tower
🗽	statue_of_liberty
⛪	church
🕌	mosque
🛕	hindu_temple
🕍	synagogue
⛩️	shinto_shrine
🕋	kaaba
⛲	fountain
⛺	tent
🌁	foggy
🌃	night_with_stars
🏙️	cityscape
🌄	sunrise_over_mountains
🌅	sunrise
🌆	city_sunset	cityscape at dusk
🌇	city_sunrise	sunset over buildings
🌉	bridge_at_night
♨️	hotsprings	hot springs
🎠	carousel_horse
🛝	playground_slide
🎡	ferris_wheel
🎢	roller_coaster
💈	barber	pole
🎪	circus_tent
🚂	steam_locomotive
🚃	railway_car
🚄	bullettrain_side	high-speed train
🚅	bullettrain_front	high-speed train bullet nose
🚆	train2	train
🚇	metro
🚈	light_rail
🚉	station
🚊	tram
🚝	monorail
🚞	mountain_railway
🚋	train	tram car
🚌	bus
🚍	oncoming_bus
🚎	trolleybus
🚐	minibus
🚑	ambulance
🚒	fire_engine
🚓	police_car
🚔	oncoming_police_car
🚕	taxi
🚖	oncoming_taxi
🚗	car red_car	automobile
🚘	oncoming_automobile
🚙	blue_car	recreational vehicle
🛻	pickup_truck
🚚	truck	delivery
🚛	articulated_lorry
🚜	tractor
🏎️	racing_car
🏍️	racing_motorcycle
🛵	motor_scooter
🦽	manual_wheelchair
🦼	motorized_wheelchair
🛺	auto_rickshaw
🚲	bike	bicycle
🛴	scooter
🛹	skateboard
🛼	roller_skate
🚏	busstop	bus stop
🛣️	motorway
🛤️	railway_track
🛢️	oil_drum
⛽	fuelpump	fuel pump
🛞	wheel
🚨	rotating_light	police cars revolving
🚥	traffic_light	horizontal
🚦	vertical_traffic_light
🛑	octagonal_sign
🚧	construction	sign
⚓	anchor
🛟	ring_buoy
⛵	boat sailboat
🛶	canoe
🚤	speedboat
🛳️	passenger_ship
⛴️	ferry
🛥️	motor_boat
🚢	ship
✈️	airplane
🛩️	small_airplane
🛫	airplane_departure
🛬	airplane_arriving
🪂	parachute
💺	seat
🚁	helicopter
🚟	suspension_railway
🚠	mountain_cableway
🚡	aerial_tramway
🛰️	satellite
🚀	rocket
🛸	flying_saucer
🛎️	bellhop_bell
🧳	luggage
⌛	hourglass
⏳	hourglass_flowing_sand
⌚	watch
⏰	alarm_clock
⏱️	stopwatch
⏲️	timer_clock
🕰️	mantelpiece_clock
🕛	clock12	clock face twelve oclock
🕧	clock1230	clock face twelve-thirty
🕐	clock1	clock face one oclock
🕜	clock130	clock face one-thirty
🕑	clock2	clock face two oclock
🕝	clock230	clock face two-thirty
🕒	clock3	clock face three oclock
🕞	clock330	clock face three-thirty
🕓	clock4	clock face four oclock
🕟	clock430	clock face four-thirty
🕔	clock5	clock face five oclock
🕠	clock530	clock face five-thirty
🕕	clock6	clock face six oclock
🕡	clock630	clock face six-thirty
🕖	clock7	clock face seven oclock
🕢	clock730	clock face seven-thirty
🕗	clock8	clock face eight oclock
🕣	clock830	clock face eight-thirty
🕘	clock9	clock face nine oclock
🕤	clock930	clock face nine-thirty
🕙	clock10	clock face ten oclock
🕥	clock1030	clock face ten-thirty
🕚	clock11	clock face eleven oclock
🕦	clock1130	clock face eleven-thirty
🌑	new_moon	symbol
🌒	waxing_crescent_moon	symbol
🌓	first_quarter_moon	symbol
🌔	moon waxing_gibbous_moon	symbol
🌕	full_moon	symbol
🌖	waning_gibbous_moon	symbol
🌗	last_quarter_moon	symbol
🌘	waning_crescent_moon	symbol
🌙	crescent_moon
🌚	new_moon_with_face
🌛	first_quarter_moon_with_face
🌜	last_quarter_moon_with_face
🌡️	thermometer
☀️	sunny	black sun rays
🌝	full_moon_with_face
🌞	sun_with_face
🪐	ringed_planet
⭐	star	white medium
🌟	star2	glowing star
🌠	stars	shooting star
🌌	milky_way
☁️	cloud
⛅	partly_sunny	sun behind cloud
⛈️	thunder_cloud_and_rain	lightning
🌤️	mostly_sunny sun_small_cloud	behind
🌥️	barely_sunny sun_behind_cloud	large
🌦️	partly_sunny_rain sun_behind_rain_cloud
🌧️	rain_cloud
🌨️	snow_cloud
🌩️	lightning lightning_cloud
🌪️	tornado tornado_cloud
🌫️	fog
🌬️	wind_blowing_face
🌀	cyclone
🌈	rainbow
🌂	closed_umbrella
☂️	umbrella
☔	umbrella_with_rain_drops
⛱️	umbrella_on_ground
⚡	zap	high voltage sign
❄️	snowflake
☃️	snowman
⛄	snowman_without_snow
☄️	comet
🔥	fire
💧	droplet
🌊	ocean	water wave
🎃	jack_o_lantern	jack-o-lantern
🎄	christmas_tree
🎆	fireworks
🎇	sparkler	firework
🧨	firecracker
✨	sparkles
🎈	balloon
🎉	tada	party popper
🎊	confetti_ball
🎋	tanabata_tree
🎍	bamboo	pine decoration
🎎	dolls	japanese
🎏	flags	carp streamer
🎐	wind_chime
🎑	rice_scene	moon viewing ceremony
🧧	red_envelope	gift
🎀	ribbon
🎁	gift	wrapped present
🎗️	reminder_ribbon
🎟️	admission_tickets
🎫	ticket
🎖️	medal	military
🏆	trophy
🏅	sports_medal
🥇	first_place_medal
🥈	second_place_medal
🥉	third_place_medal
⚽	soccer	ball
⚾	baseball
🥎	softball
🏀	basketball	hoop
🏐	volleyball
🏈	football	american
🏉	rugby_football
🎾	tennis	racquet ball
🥏	flying_disc
🎳	bowling
🏏	cricket_bat_and_ball
🏑	field_hockey_stick_and_ball
🏒	ice_hockey_stick_and_puck
🥍	lacrosse	stick ball
🏓	table_tennis_paddle_and_ball
🏸	badminton_racquet_and_shuttlecock
🥊	boxing_glove
🥋	martial_arts_uniform
🥅	goal_net
⛳	golf	flag hole
⛸️	ice_skate
🎣	fishing_pole_and_fish
🤿	diving_mask
🎽	running_shirt_with_sash
🎿	ski	boot
🛷	sled
🥌	curling_stone
🎯	dart	direct hit
🪀	yo-yo
🪁	kite
🔫	gun	pistol
🎱	8ball	billiards
🔮	crystal_ball
🪄	magic_wand
🎮	video_game
🕹️	joystick
🎰	slot_machine
🎲	game_die
🧩	jigsaw	puzzle piece
🧸	teddy_bear
🪅	pinata
🪩	mirror_ball
🪆	nesting_dolls
♠️	spades	black spade suit
♥️	hearts	black heart suit
♦️	diamonds	black diamond suit
♣️	clubs	black club suit
♟️	chess_pawn
🃏	black_joker	playing card
🀄	mahjong	tile red dragon
🎴	flower_playing_cards
🎭	performing_arts
🖼️	frame_with_picture	framed
🎨	art	artist palette
🧵	thread	spool
🪡	sewing_needle
🧶	yarn	ball
🪢	knot
👓	eyeglasses
🕶️	dark_sunglasses
🥽	goggles
🥼	lab_coat
🦺	safety_vest
👔	necktie
👕	shirt tshirt	t-shirt
👖	jeans
🧣	scarf
🧤	gloves
🧥	coat
🧦	socks
👗	dress
👘	kimono
🥻	sari
🩱	one-piece_swimsuit	one-piece
🩲	briefs
🩳	shorts
👙	bikini
👚	womans_clothes
🪭	folding_hand_fan
👛	purse
👜	handbag
👝	pouch
🛍️	shopping_bags
🎒	school_satchel
🩴	thong_sandal
👞	mans_shoe shoe
👟	athletic_shoe
🥾	hiking_boot
🥿	womans_flat_shoe
👠	high_heel	high-heeled shoe
👡	sandal	womans
🩰	ballet_shoes
👢	boot	womans boots
🪮	hair_pick
👑	crown
👒	womans_hat
🎩	tophat	top hat
🎓	mortar_board	graduation cap
🧢	billed_cap
🪖	military_helmet
⛑️	helmet_with_white_cross	rescue worker s
📿	prayer_beads
💄	lipstick
💍	ring
💎	gem	stone
🔇	mute	speaker cancellation stroke
🔈	speaker
🔉	sound	speaker one wave
🔊	loud_sound	speaker three waves
📢	loudspeaker	public address
📣	mega	cheering megaphone
📯	postal_horn
🔔	bell
🔕	no_bell	cancellation stroke
🎼	musical_score
🎵	musical_note
🎶	notes	multiple musical
🎙️	studio_microphone
🎚️	level_slider
🎛️	control_knobs
🎤	microphone
🎧	headphones	headphone
📻	radio
🎷	saxophone
🪗	accordion
🎸	guitar
🎹	musical_keyboard
🎺	trumpet
🎻	violin
🪕	banjo
🥁	drum_with_drumsticks
🪘	long_drum
🪇	maracas
🪈	flute
🪉	harp
📱	iphone	mobile phone
📲	calling	mobile phone rightwards arrow at left
☎️	phone telephone	black
📞	telephone_receiver
📟	pager
📠	fax	machine
🔋	battery
🪫	low_battery
🔌	electric_plug
💻	computer	personal
🖥️	desktop_computer
🖨️	printer
⌨️	keyboard
🖱️	three_button_mouse	computer
🖲️	trackball
💽	minidisc
💾	floppy_disk
💿	cd	optical disc
📀	dvd
🧮	abacus
🎥	movie_camera
🎞️	film_frames
📽️	film_projector
🎬	clapper	board
📺	tv	television
📷	camera
📸	camera_with_flash
📹	video_camera
📼	vhs	videocassette
🔍	mag	left-pointing magnifying glass
🔎	mag_right	right-pointing magnifying glass
🕯️	candle
💡	bulb	electric light
🔦	flashlight	electric torch
🏮	izakaya_lantern lantern
🪔	diya_lamp
📔	notebook_with_decorative_cover
📕	closed_book
📖	book open_book
📗	green_book
📘	blue_book
📙	orange_book
📚	books
📓	notebook
📒	ledger
📃	page_with_curl
📜	scroll
📄	page_facing_up
📰	newspaper
🗞️	rolled_up_newspaper	rolled-up
📑	bookmark_tabs
🔖	bookmark
🏷️	label
💰	moneybag	money bag
🪙	coin
💴	yen	banknote sign
💵	dollar	banknote sign
💶	euro	banknote sign
💷	pound	banknote sign
💸	money_with_wings
💳	credit_card
🧾	receipt
💹	chart	upwards trend yen sign
✉️	email envelope
📧	e-mail	symbol
📨	incoming_envelope
📩	envelope_with_arrow	downwards above
📤	outbox_tray
📥	inbox_tray
📦	package
📫	mailbox	closed raised flag
📪	mailbox_closed	lowered flag
📬	mailbox_with_mail	open raised flag
📭	mailbox_with_no_mail	open lowered flag
📮	postbox
🗳️	ballot_box_with_ballot
✏️	pencil2	pencil
✒️	black_nib
🖋️	lower_left_fountain_pen
🖊️	lower_left_ballpoint_pen
🖌️	lower_left_paintbrush
🖍️	lower_left_crayon
📝	memo pencil
💼	briefcase
📁	file_folder
📂	open_file_folder
🗂️	card_index_dividers
📅	date	calendar
📆	calendar	tear-off
🗒️	spiral_note_pad	notepad
🗓️	spiral_calendar_pad
📇	card_index
📈	chart_with_upwards_trend
📉	chart_with_downwards_trend
📊	bar_chart
📋	clipboard
📌	pushpin
📍	round_pushpin
📎	paperclip
🖇️	linked_paperclips
📏	straight_ruler
📐	triangular_ruler
✂️	scissors	black
🗃️	card_file_box
🗄️	file_cabinet
🗑️	wastebasket
🔒	lock
🔓	unlock	open lock
🔏	lock_with_ink_pen
🔐	closed_lock_with_key
🔑	key
🗝️	old_key
🔨	hammer
🪓	axe
⛏️	pick
⚒️	hammer_and_pick
🛠️	hammer_and_wrench
🗡️	dagger_knife
⚔️	crossed_swords
💣	bomb
🪃	boomerang
🏹	bow_and_arrow
🛡️	shield
🪚	carpentry_saw
🔧	wrench
🪛	screwdriver
🔩	nut_and_bolt
⚙️	gear
🗜️	compression	clamp
⚖️	scales	balance scale
🦯	probing_cane
🔗	link	symbol
⛓️‍💥	broken_chain
⛓️	chains
🪝	hook
🧰	toolbox
🧲	magnet
🪜	ladder
🪏	shovel
⚗️	alembic
🧪	test_tube
🧫	petri_dish
🧬	dna	double helix
🔬	microscope
🔭	telescope
📡	satellite_antenna
💉	syringe
🩸	drop_of_blood
💊	pill
🩹	adhesive_bandage
🩼	crutch
🩺	stethoscope
🩻	x-ray
🚪	door
🛗	elevator
🪞	mirror
🪟	window
🛏️	bed
🛋️	couch_and_lamp
🪑	chair
🚽	toilet
🪠	plunger
🚿	shower
🛁	bathtub
🪤	mouse_trap
🪒	razor
🧴	lotion_bottle
🧷	safety_pin
🧹	broom
🧺	basket
🧻	roll_of_paper
🪣	bucket
🧼	soap	bar
🫧	bubbles
🪥	toothbrush
🧽	sponge
🧯	fire_extinguisher
🛒	shopping_trolley
🚬	smoking	symbol
⚰️	coffin
🪦	headstone
⚱️	funeral_urn
🧿	nazar_amulet
🪬	hamsa
🗿	moyai
🪧	placard
🪪	identification_card
🏧	atm	automated teller machine
🚮	put_litter_in_its_place	symbol
🚰	potable_water	symbol
♿	wheelchair	symbol
🚹	mens	symbol
🚺	womens	symbol
🚻	restroom
🚼	baby_symbol
🚾	wc	water closet
🛂	passport_control
🛃	customs
🛄	baggage_claim
🛅	left_luggage
⚠️	warning	sign
🚸	children_crossing
⛔	no_entry
🚫	no_entry_sign
🚳	no_bicycles
🚭	no_smoking	symbol
🚯	do_not_litter	symbol
🚱	non-potable_water	non-potable symbol
🚷	no_pedestrians
📵	no_mobile_phones
🔞	underage	no one under eighteen symbol
☢️	radioactive_sign
☣️	biohazard_sign
⬆️	arrow_up	upwards black
↗️	arrow_upper_right	north east
➡️	arrow_right	black rightwards
↘️	arrow_lower_right	south east
⬇️	arrow_down	downwards black
↙️	arrow_lower_left	south west
⬅️	arrow_left	leftwards black
↖️	arrow_upper_left	north west
↕️	arrow_up_down
↔️	left_right_arrow
↩️	leftwards_arrow_with_hook
↪️	arrow_right_hook	rightwards
⤴️	arrow_heading_up	pointing rightwards then curving upwards
⤵️	arrow_heading_down	pointing rightwards then curving downwards
🔃	arrows_clockwise	downwards upwards open circle
🔄	arrows_counterclockwise	anticlockwise downwards upwards open circle
🔙	back	leftwards arrow above
🔚	end	leftwards arrow above
🔛	on	exclamation mark left right arrow above
🔜	soon	rightwards arrow above
🔝	top	upwards arrow above
🛐	place_of_worship
⚛️	atom_symbol
🕉️	om_symbol
✡️	star_of_david
☸️	wheel_of_dharma
☯️	yin_yang
✝️	latin_cross
☦️	orthodox_cross
☪️	star_and_crescent
☮️	peace_symbol
🕎	menorah_with_nine_branches
🔯	six_pointed_star	middle dot
🪯	khanda
♈	aries
♉	taurus
♊	gemini
♋	cancer
♌	leo
♍	virgo
♎	libra
♏	scorpius
♐	sagittarius
♑	capricorn
♒	aquarius
♓	pisces
⛎	ophiuchus
🔀	twisted_rightwards_arrows
🔁	repeat	clockwise rightwards leftwards open circle arrows
🔂	repeat_one	clockwise rightwards leftwards open circle arrows circled overlay
▶️	arrow_forward	black right-pointing triangle
⏩	fast_forward	black right-pointing double triangle
⏭️	black_right_pointing_double_triangle_with_vertical_bar	next track button
⏯️	black_right_pointing_triangle_with_double_vertical_bar	play pause button
◀️	arrow_backward	black left-pointing triangle
⏪	rewind	black left-pointing double triangle
⏮️	black_left_pointing_double_triangle_with_vertical_bar	last track button
🔼	arrow_up_small	up-pointing red triangle
⏫	arrow_double_up	black up-pointing triangle
🔽	arrow_down_small	down-pointing red triangle
⏬	arrow_double_down	black down-pointing triangle
⏸️	double_vertical_bar	pause button
⏹️	black_square_for_stop	button
⏺️	black_circle_for_record	button
⏏️	eject	button
🎦	cinema
🔅	low_brightness	symbol
🔆	high_brightness	symbol
📶	signal_strength	antenna bars
🛜	wireless
📳	vibration_mode
📴	mobile_phone_off
♀️	female_sign
♂️	male_sign
⚧️	transgender_symbol
✖️	heavy_multiplication_x
➕	heavy_plus_sign
➖	heavy_minus_sign
➗	heavy_division_sign
🟰	heavy_equals_sign
♾️	infinity
‼️	bangbang	double exclamation mark
⁉️	interrobang	exclamation question mark
❓	question	black mark ornament
❔	grey_question	white mark ornament
❕	grey_exclamation	white mark ornament
❗	exclamation heavy_exclamation_mark	symbol
〰️	wavy_dash
💱	currency_exchange
💲	heavy_dollar_sign
⚕️	medical_symbol staff_of_aesculapius
♻️	recycle	black universal recycling symbol
⚜️	fleur_de_lis	fleur-de-lis
🔱	trident	emblem
📛	name_badge
🔰	beginner	japanese symbol
⭕	o	heavy large circle
✅	white_check_mark	heavy
☑️	ballot_box_with_check
✔️	heavy_check_mark
❌	x	cross mark
❎	negative_squared_cross_mark
➰	curly_loop
➿	loop	double curly
〽️	part_alternation_mark
✳️	eight_spoked_asterisk
✴️	eight_pointed_black_star
❇️	sparkle
©️	copyright	sign
®️	registered	sign
™️	tm	trade mark sign
🫟	splatter
#️⃣	hash	key
*️⃣	keycap_star
0️⃣	zero	keycap 0
1️⃣	one	keycap 1
2️⃣	two	keycap 2
3️⃣	three	keycap 3
4️⃣	four	keycap 4
5️⃣	five	keycap 5
6️⃣	six	keycap 6
7️⃣	seven	keycap 7
8️⃣	eight	keycap 8
9️⃣	nine	keycap 9
🔟	keycap_ten
🔠	capital_abcd	input symbol latin letters
🔡	abcd	input symbol latin small letters
🔢	1234	input symbol numbers
🔣	symbols	input symbol
🔤	abc	input symbol latin letters
🅰️	a	negative squared latin capital letter
🆎	ab	negative squared
🅱️	b	negative squared latin capital letter
🆑	cl	squared
🆒	cool	squared
🆓	free	squared
ℹ️	information_source
🆔	id	squared
Ⓜ️	m	circled latin capital letter
🆕	new	squared
🆖	ng	squared
🅾️	o2	negative squared latin capital letter o
🆗	ok	squared
🅿️	parking	negative squared latin capital letter p
🆘	sos	squared
🆙	up	squared exclamation mark
🆚	vs	squared
🈁	koko	squared katakana
🈂️	sa	squared katakana
🈷️	u6708	squared cjk unified ideograph-6708
🈶	u6709	squared cjk unified ideograph-6709
🈯	u6307	squared cjk unified ideograph-6307
🉐	ideograph_advantage	circled
🈹	u5272	squared cjk unified ideograph-5272
🈚	u7121	squared cjk unified ideograph-7121
🈲	u7981	squared cjk unified ideograph-7981
🉑	accept	circled ideograph
🈸	u7533	squared cjk unified ideograph-7533
🈴	u5408	squared cjk unified ideograph-5408
🈳	u7a7a	squared cjk unified ideograph-7a7a
㊗️	congratulations	circled ideograph congratulation
㊙️	secret	circled ideograph
🈺	u55b6	squared cjk unified ideograph-55b6
🈵	u6e80	squared cjk unified ideograph-6e80
🔴	red_circle	large
🟠	large_orange_circle
🟡	large_yellow_circle
🟢	large_green_circle
🔵	large_blue_circle
🟣	large_purple_circle
🟤	large_brown_circle
⚫	black_circle	medium
⚪	white_circle	medium
🟥	large_red_square
🟧	large_orange_square
🟨	large_yellow_square
🟩	large_green_square
🟦	large_blue_square
🟪	large_purple_square
🟫	large_brown_square
⬛	black_large_square
⬜	white_large_square
◼️	black_medium_square
◻️	white_medium_square
◾	black_medium_small_square
◽	white_medium_small_square
▪️	black_small_square
▫️	white_small_square
🔶	large_orange_diamond
🔷	large_blue_diamond
🔸	small_orange_diamond
🔹	small_blue_diamond
🔺	small_red_triangle	up-pointing
🔻	small_red_triangle_down	down-pointing
💠	diamond_shape_with_a_dot_inside
🔘	radio_button
🔳	white_square_button
🔲	black_square_button
🏁	checkered_flag	chequered
🚩	triangular_flag_on_post
🎌	crossed_flags
🏴	waving_black_flag
🏳️	waving_white_flag
🏳️‍🌈	rainbow-flag
🏳️‍⚧️	transgender_flag
🏴‍☠️	pirate_flag
🇦🇨	flag-ac	ascension island
🇦🇩	flag-ad	andorra
🇦🇪	flag-ae	united arab emirates
🇦🇫	flag-af	afghanistan
🇦🇬	flag-ag	antigua barbuda
🇦🇮	flag-ai	anguilla
🇦🇱	flag-al	albania
🇦🇲	flag-am	armenia
🇦🇴	flag-ao	angola
🇦🇶	flag-aq	antarctica
🇦🇷	flag-ar	argentina
🇦🇸	flag-as	american samoa
🇦🇹	flag-at	austria
🇦🇺	flag-au	australia
🇦🇼	flag-aw	aruba
🇦🇽	flag-ax	land islands
🇦🇿	flag-az	azerbaijan
🇧🇦	flag-ba	bosnia herzegovina
🇧🇧	flag-bb	barbados
🇧🇩	flag-bd	bangladesh
🇧🇪	flag-be	belgium
🇧🇫	flag-bf	burkina faso
🇧🇬	flag-bg	bulgaria
🇧🇭	flag-bh	bahrain
🇧🇮	flag-bi	burundi
🇧🇯	flag-bj	benin
🇧🇱	flag-bl	st barth lemy
🇧🇲	flag-bm	bermuda
🇧🇳	flag-bn	brunei
🇧🇴	flag-bo	bolivia
🇧🇶	flag-bq	caribbean netherlands
🇧🇷	flag-br	brazil
🇧🇸	flag-bs	bahamas
🇧🇹	flag-bt	bhutan
🇧🇻	flag-bv	bouvet island
🇧🇼	flag-bw	botswana
🇧🇾	flag-by	belarus
🇧🇿	flag-bz	belize
🇨🇦	flag-ca	canada
🇨🇨	flag-cc	cocos keeling islands
🇨🇩	flag-cd	congo - kinshasa
🇨🇫	flag-cf	central african republic
🇨🇬	flag-cg	congo - brazzaville
🇨🇭	flag-ch	switzerland
🇨🇮	flag-ci	c te d ivoire
🇨🇰	flag-ck	cook islands
🇨🇱	flag-cl	chile
🇨🇲	flag-cm	cameroon
🇨🇳	cn flag-cn	china
🇨🇴	flag-co	colombia
🇨🇵	flag-cp	clipperton island
🇨🇶	flag-sark
🇨🇷	flag-cr	costa rica
🇨🇺	flag-cu	cuba
🇨🇻	flag-cv	cape verde
🇨🇼	flag-cw	cura ao
🇨🇽	flag-cx	christmas island
🇨🇾	flag-cy	cyprus
🇨🇿	flag-cz	czechia
🇩🇪	de flag-de	germany
🇩🇬	flag-dg	diego garcia
🇩🇯	flag-dj	djibouti
🇩🇰	flag-dk	denmark
🇩🇲	flag-dm	dominica
🇩🇴	flag-do	dominican republic
🇩🇿	flag-dz	algeria
🇪🇦	flag-ea	ceuta melilla
🇪🇨	flag-ec	ecuador
🇪🇪	flag-ee	estonia
🇪🇬	flag-eg	egypt
🇪🇭	flag-eh	western sahara
🇪🇷	flag-er	eritrea
🇪🇸	es flag-es	spain
🇪🇹	flag-et	ethiopia
🇪🇺	flag-eu	european union
🇫🇮	flag-fi	finland
🇫🇯	flag-fj	fiji
🇫🇰	flag-fk	falkland islands
🇫🇲	flag-fm	micronesia
🇫🇴	flag-fo	faroe islands
🇫🇷	fr flag-fr	france
🇬🇦	flag-ga	gabon
🇬🇧	gb uk flag-gb	united kingdom
🇬🇩	flag-gd	grenada
🇬🇪	flag-ge	georgia
🇬🇫	flag-gf	french guiana
🇬🇬	flag-gg	guernsey
🇬🇭	flag-gh	ghana
🇬🇮	flag-gi	gibraltar
🇬🇱	flag-gl	greenland
🇬🇲	flag-gm	gambia
🇬🇳	flag-gn	guinea
🇬🇵	flag-gp	guadeloupe
🇬🇶	flag-gq	equatorial guinea
🇬🇷	flag-gr	greece
🇬🇸	flag-gs	south georgia sandwich islands
🇬🇹	flag-gt	guatemala
🇬🇺	flag-gu	guam
🇬🇼	flag-gw	guinea-bissau
🇬🇾	flag-gy	guyana
🇭🇰	flag-hk	hong kong sar china
🇭🇲	flag-hm	heard mcdonald islands
🇭🇳	flag-hn	honduras
🇭🇷	flag-hr	croatia
🇭🇹	flag-ht	haiti
🇭🇺	flag-hu	hungary
🇮🇨	flag-ic	canary islands
🇮🇩	flag-id	indonesia
🇮🇪	flag-ie	ireland
🇮🇱	flag-il	israel
🇮🇲	flag-im	isle man
🇮🇳	flag-in	india
🇮🇴	flag-io	british indian ocean territory
🇮🇶	flag-iq	iraq
🇮🇷	flag-ir	iran
🇮🇸	flag-is	iceland
🇮🇹	it flag-it	italy
🇯🇪	flag-je	jersey
🇯🇲	flag-jm	jamaica
🇯🇴	flag-jo	jordan
🇯🇵	jp flag-jp	japan
🇰🇪	flag-ke	kenya
🇰🇬	flag-kg	kyrgyzstan
🇰🇭	flag-kh	cambodia
🇰🇮	flag-ki	kiribati
🇰🇲	flag-km	comoros
🇰🇳	flag-kn	st kitts nevis
🇰🇵	flag-kp	north korea
🇰🇷	kr flag-kr	south korea
🇰🇼	flag-kw	kuwait
🇰🇾	flag-ky	cayman islands
🇰🇿	flag-kz	kazakhstan
🇱🇦	flag-la	laos
🇱🇧	flag-lb	lebanon
🇱🇨	flag-lc	st lucia
🇱🇮	flag-li	liechtenstein
🇱🇰	flag-lk	sri lanka
🇱🇷	flag-lr	liberia
🇱🇸	flag-ls	lesotho
🇱🇹	flag-lt	lithuania
🇱🇺	flag-lu	luxembourg
🇱🇻	flag-lv	latvia
🇱🇾	flag-ly	libya
🇲🇦	flag-ma	morocco
🇲🇨	flag-mc	monaco
🇲🇩	flag-md	moldova
🇲🇪	flag-me	montenegro
🇲🇫	flag-mf	st martin
🇲🇬	flag-mg	madagascar
🇲🇭	flag-mh	marshall islands
🇲🇰	flag-mk	north macedonia
🇲🇱	flag-ml	mali
🇲🇲	flag-mm	myanmar burma
🇲🇳	flag-mn	mongolia
🇲🇴	flag-mo	macao sar china
🇲🇵	flag-mp	northern mariana islands
🇲🇶	flag-mq	martinique
🇲🇷	flag-mr	mauritania
🇲🇸	flag-ms	montserrat
🇲🇹	flag-mt	malta
🇲🇺	flag-mu	mauritius
🇲🇻	flag-mv	maldives
🇲🇼	flag-mw	malawi
🇲🇽	flag-mx	mexico
🇲🇾	flag-my	malaysia
🇲🇿	flag-mz	mozambique
🇳🇦	flag-na	namibia
🇳🇨	flag-nc	new caledonia
🇳🇪	flag-ne	niger
🇳🇫	flag-nf	norfolk island
🇳🇬	flag-ng	nigeria
🇳🇮	flag-ni	nicaragua
🇳🇱	flag-nl	netherlands
🇳🇴	flag-no	norway
🇳🇵	flag-np	nepal
🇳🇷	flag-nr	nauru
🇳🇺	flag-nu	niue
🇳🇿	flag-nz	new zealand
🇴🇲	flag-om	oman
🇵🇦	flag-pa	panama
🇵🇪	flag-pe	peru
🇵🇫	flag-pf	french polynesia
🇵🇬	flag-pg	papua new guinea
🇵🇭	flag-ph	philippines
🇵🇰	flag-pk	pakistan
🇵🇱	flag-pl	poland
🇵🇲	flag-pm	st pierre miquelon
🇵🇳	flag-pn	pitcairn islands
🇵🇷	flag-pr	puerto rico
🇵🇸	flag-ps	palestinian territories
🇵🇹	flag-pt	portugal
🇵🇼	flag-pw	palau
🇵🇾	flag-py	paraguay
🇶🇦	flag-qa	qatar
🇷🇪	flag-re	r union
🇷🇴	flag-ro	romania
🇷🇸	flag-rs	serbia
🇷🇺	ru flag-ru	russia
🇷🇼	flag-rw	rwanda
🇸🇦	flag-sa	saudi arabia
🇸🇧	flag-sb	solomon islands
🇸🇨	flag-sc	seychelles
🇸🇩	flag-sd	sudan
🇸🇪	flag-se	sweden
🇸🇬	flag-sg	singapore
🇸🇭	flag-sh	st helena
🇸🇮	flag-si	slovenia
🇸🇯	flag-sj	svalbard jan mayen
🇸🇰	flag-sk	slovakia
🇸🇱	flag-sl	sierra leone
🇸🇲	flag-sm	san marino
🇸🇳	flag-sn	senegal
🇸🇴	flag-so	somalia
🇸🇷	flag-sr	suriname
🇸🇸	flag-ss	south sudan
🇸🇹	flag-st	s o tom pr ncipe
🇸🇻	flag-sv	el salvador
🇸🇽	flag-sx	sint maarten
🇸🇾	flag-sy	syria
🇸🇿	flag-sz	eswatini
🇹🇦	flag-ta	tristan da cunha
🇹🇨	flag-tc	turks caicos islands
🇹🇩	flag-td	chad
🇹🇫	flag-tf	french southern territories
🇹🇬	flag-tg	togo
🇹🇭	flag-th	thailand
🇹🇯	flag-tj	tajikistan
🇹🇰	flag-tk	tokelau
🇹🇱	flag-tl	timor-leste
🇹🇲	flag-tm	turkmenistan
🇹🇳	flag-tn	tunisia
🇹🇴	flag-to	tonga
🇹🇷	flag-tr	t rkiye
🇹🇹	flag-tt	trinidad tobago
🇹🇻	flag-tv	tuvalu
🇹🇼	flag-tw	taiwan
🇹🇿	flag-tz	tanzania
🇺🇦	flag-ua	ukraine
🇺🇬	flag-ug	uganda
🇺🇲	flag-um	u s outlying islands
🇺🇳	flag-un	united nations
🇺🇸	us flag-us	united states
🇺🇾	flag-uy	uruguay
🇺🇿	flag-uz	uzbekistan
🇻🇦	flag-va	vatican city
🇻🇨	flag-vc	st vincent grenadines
🇻🇪	flag-ve	venezuela
🇻🇬	flag-vg	british virgin islands
🇻🇮	flag-vi	u s virgin islands
🇻🇳	flag-vn	vietnam
🇻🇺	flag-vu	vanuatu
🇼🇫	flag-wf	wallis futuna
🇼🇸	flag-ws	samoa
🇽🇰	flag-xk	kosovo
🇾🇪	flag-ye	yemen
🇾🇹	flag-yt	mayotte
🇿🇦	flag-za	south africa
🇿🇲	flag-zm	zambia
🇿🇼	flag-zw	zimbabwe
🏴󠁧󠁢󠁥󠁮󠁧󠁿	flag-england
🏴󠁧󠁢󠁳󠁣󠁴󠁿	flag-scotland
🏴󠁧󠁢󠁷󠁬󠁳󠁿	flag-wales`;
