reject:
  # blocked by the ESLint v9 support of eslint-config-airbnb-base
  # https://github.com/airbnb/javascript/issues/2961
  - eslint
  - eslint-plugin-svelte
  # need to investigate an infinite loop and migrate to Shiki
  - lexical
  - "@lexical/*"
  # https://github.com/gajus/eslint-plugin-jsdoc/issues/1478
  - eslint-plugin-jsdoc
