version: '0.2'
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - '**/.*'
  - '**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}'
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - data/**/*.json
  - src/**/generated.js
  - src/lib/locales/*.yaml
  - '!src/lib/locales/en-*.yaml'
words:
  - atrule
  - beforeinput
  - colour
  - colours
  - cooldown
  - CVEs
  - esbuild
  - espree
  - esrap
  - GHSA
  - Ghsas
  - iamcal
  - infobar
  - jsdoc
  - Klass
  - Kohei
  - localizers
  - moyai
  - nocheck
  - oninputcapture
  - onpointerrawupdate
  - opsz
  - oxlint
  - plainify
  - plusplus
  - pnpm
  - pointerrawupdate
  - postcss
  - Shiki
  - shikijs
  - singleline
  - spritesheet
  - strikethrough
  - stylelint
  - sveltejs
  - Sveltia
  - thumbsup
  - tokenize
  - typedefs
  - unclickable
  - unhighlighted
  - unpkg
  - unrs
  - unstub
  - Vite
  - Vitest
  - wght
  - Yoshino
