version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - data/**/*.json
  - src/lib/locales/*.yaml
  - "!src/lib/locales/en-*.yaml"
words:
  - atrule
  - beforeinput
  - colour
  - colours
  - cooldown
  - CVEs
  - esbuild
  - espree
  - GHSA
  - Ghsas
  - infobar
  - jsdoc
  - Kohei
  - nocheck
  - oninputcapture
  - onpointerrawupdate
  - opsz
  - oxlint
  - plusplus
  - pnpm
  - pointerrawupdate
  - postcss
  - prismjs
  - Shiki
  - singleline
  - strikethrough
  - stylelint
  - sveltejs
  - Sveltia
  - typedefs
  - unrs
  - Vite
  - Vitest
  - wght
  - Yoshino
