minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - devalue
  - svelte
  - "@sveltejs/*"
  - "@sveltia/*"

overrides:
  "cookie@<0.7.0": ">=0.7.0"
  "esbuild@<=0.24.2": ">=0.25.0"

onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess

auditConfig:
  ignoreCves:
    # ESLint https://github.com/advisories/GHSA-p5wg-g6qr-c7cg
    - CVE-2025-50537
