allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  svelte-preprocess: true
  unrs-resolver: false

engineStrict: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - lexical
  - "@lexical/*"
  - "@sveltia/*"

overrides:
  # <0.7.0 has a security vulnerability, 2.0.0 causes issues with SvelteKit
  "cookie@<0.7.0": "^1.0.0"
