minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - devalue
  - svelte
  - "@sveltejs/*"
  - "@sveltia/*"

overrides:
  "cookie@<0.7.0": ">=0.7.0"
  "esbuild@<=0.24.2": ">=0.25.0"

onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess

auditConfig:
  ignoreGhsas:
    # https://github.com/advisories/GHSA-3ppc-4f35-3m26
    - GHSA-3ppc-4f35-3m26
