// Generated by `scripts/generate-shiki-metadata.js`. DO NOT EDIT.

/**
 * Version of this package, used to resolve the prebuilt Shiki engine chunk from a CDN.
 */
export const UI_VERSION = '0.69.1';
