# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package to npmjs

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: pnpm install
      - name: Build & publish the app
        run: pnpm publish
